project_filepath: "data/01_raw/project.xlsx"
organization_filepath: "data/01_raw/organization.xlsx"

model_filepath: "data/06_models/best_model.pkl"
metrics_filepath: "data/08_reporting/all_metrics.json"

contamination: 0.01
target_column: "funding_class"


mlflow_tracking_uri: "file:///$(project_root)/mlruns"

numeric_columns:
  - org_count
  - duration_days
